server:
  port: 9090
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anandayadav/Majorproject-config-properties.git
          clone-on-start: true
          
management:
  security:
   enabled: false